#!/bin/bash -e

# curl -Lo setup https://bit.ly/1hpb83X
# chmod a+x setup
# ./setup

# You will need nomodeset on the Vostro.

read -rp "Hostname: " hostname
read -rp "Main device: " disk_device
read -rp "USB boot device: " usb_device
read -rp "Timezone: " timezone

fdisk "$usb_device" << 'EOF'
o
n
p
1


a
w
EOF

mountpoint=$(mktemp -d)

mkfs.ext4 -L "$hostname"-/boot "$usb_device"1

while ! cryptsetup -y --hash sha512 --cipher twofish-xts-plain64 --key-size 512 --offset 0 open --type=plain "$disk_device" root; do :; done
mkfs.ext4 -L "$hostname"-/ /dev/mapper/root

mount /dev/mapper/root "$mountpoint"
mkdir "$mountpoint"/boot
mount LABEL="$hostname"-/boot "$mountpoint"/boot

pacman -Syy
pacman --noconfirm --ignore pacman -S reflector

reflector -f 6 -c 'United Kingdom' -c Ireland -c Netherlands --protocol http --sort rate --save /etc/pacman.d/mirrorlist

pacstrap "$mountpoint" base base-devel syslinux

cat > "$mountpoint"/etc/fstab << EOF
/dev/mapper/root      /     ext4 defaults        0 1
LABEL=$hostname-/boot /boot ext4 defaults,noauto 0 2
EOF

echo 'LANG="en_GB.UTF-8"' > "$mountpoint"/etc/locale.conf
echo "en_GB.UTF-8 UTF-8" > "$mountpoint"/etc/locale.gen
echo "$hostname" > "$mountpoint"/etc/hostname

cp /etc/pacman.d/mirrorlist "$mountpoint"/etc/pacman.d/mirrorlist

modprobe dm-mod

arch-chroot "$mountpoint" syslinux-install_update -i -a -m

root_uuid_path=$(find -L /dev/disk/by-id -samefile "$disk_device" -print -quit)

cat > "$mountpoint"/boot/syslinux/syslinux.cfg << EOF
PROMPT 0
TIMEOUT 0
DEFAULT arch

LABEL arch
    LINUX ../vmlinuz-linux
    APPEND rw root=/dev/mapper/root cryptdevice=$root_uuid_path:root:allow-discards crypto=sha512:twofish-xts-plain64:512:0:
    INITRD ../initramfs-linux.img

LABEL archfallback
    LINUX ../vmlinuz-linux
    APPEND rw root=/dev/mapper/root cryptdevice=$root_uuid_path:root:allow-discards crypto=sha512:twofish-xts-plain64:512:0:
    INITRD ../initramfs-linux-fallback.img
EOF

sed -i '/^HOOKS=/s/filesystems/encrypt &/' "$mountpoint"/etc/mkinitcpio.conf

arch-chroot "$mountpoint" mkinitcpio -p linux

arch-chroot "$mountpoint" ln -sfn /usr/share/zoneinfo/"$timezone" /etc/localtime
arch-chroot "$mountpoint" locale-gen

while ! arch-chroot "$mountpoint" passwd; do :; done
