---
- hosts: localhost
  connection: local

  vars_prompt:
    - name: config_file
      prompt: "Which vars should I load?"
      private: no
    - name: user_password
      prompt: "What should the user's password be?"
      private: yes
      encrypt: sha512_crypt
      confirm: yes

  vars_files:
    - vars/{{ config_file }}.yml

  tasks:
    - name: Get size of long to determine architecture
      command: getconf LONG_BIT
      register: long_bit
      changed_when: false

    # Used, hackily, to not reinstall AUR packages
    - name: Get list of installed packages
      command: pacman -Qq
      register: installed_packages
      changed_when: false

    - include: tasks/pacman.yml
    - include: tasks/network.yml
    - include: tasks/ssh.yml
    - include: tasks/users.yml
    - include: tasks/aur.yml
    - include: tasks/zsh.yml
    - include: tasks/sudo.yml
    - include: tasks/ntp.yml
    - include: tasks/fonts.yml
    - include: tasks/xorg.yml
    - include: tasks/blacklist-pc-speaker.yml
    - include: tasks/desktop.yml
    - include: tasks/basic-tools.yml
    - include: tasks/cron.yml
    - include: tasks/email.yml
    - include: tasks/media.yml
    - include: tasks/chinese.yml
    - include: tasks/dotfiles.yml
    - include: tasks/rbenv.yml
    - include: tasks/shared.yml

    - debug: msg={{ item }}
      with_items:
        - "Playbook complete. Remaining tasks:"
        - "- Clone and set up private dotfiles"
        - "- Import desired ssh keys to ~/.ssh/keys"
