#!/bin/sh

playbook_dir=$(mktemp -d)

trap 'rm -rf "$playbook_dir"' 0

cat > /etc/apt/sources.list.d/wheezy-backports.list << 'EOF'
deb http://ftp.jp.debian.org/debian wheezy-backports main
EOF

apt-get update
apt-get install ansible python-passlib

git clone https://github.com/cdown/ansible-personal.git "$playbook_dir"

cd "$playbook_dir"

ansible-playbook -v setup.yml
