---
- name: Copy aur script
  copy: src=files/bin/aur dest=/usr/local/bin/aur mode=755

- name: Install yaourt dependencies
  command: aur package-query
  when: "'package-query' not in installed_packages.stdout_lines"

- name: Install yaourt
  command: aur yaourt
  when: "'yaourt' not in installed_packages.stdout_lines"
