---
- name: Get list of installed packages
  command: vagrant plugin list
  register: installed_vagrant_plugins
  sudo: yes
  sudo_user: '{{ item }}'
  with_items: users
  changed_when: false

- name: Install vagrant
  yaourt: name=vagrant
  sudo: yes
  sudo_user: makepkg

- name: Install chef-dk
  yaourt: name=chef-dk
  sudo: yes
  sudo_user: makepkg

- name: Install Vagrant plugins
  command: 'vagrant plugin install {{ item }}'
  with_items:
    - vagrant-berkshelf
    - vagrant-omnibus
  sudo: yes
  sudo_user: '{{ item }}'
  with_items: users
  when: "'{{ item }}' not in installed_vagrant_plugins.stdout"

- name: Install VirtualBox (for Vagrant)
  pacman: name=virtualbox state=present
  register: virtualbox_install

# https://github.com/mitchellh/vagrant/issues/3083
- name: Remove default VirtualBox host interface to avoid failure of first vagrant up
  command: VBoxManage dhcpserver remove --netname HostInterfaceNetworking-vboxnet0
  sudo: yes
  sudo_user: '{{ item }}'
  with_items: users
  when: virtualbox_install.changed

- name: Set up autoloading of VirtualBox host modules
  copy: src=files/virtualbox/host-modules dest=/etc/modules-load.d/virtualbox-host.conf
