---
- name: Get list of installed packages
  command: vagrant plugin list
  register: installed_vagrant_plugins
  sudo: yes
  sudo_user: '{{ user }}'
  changed_when: false

- name: Install vagrant
  command: yaourt --noconfirm -S vagrant
  sudo: yes
  sudo_user: makepkg
  when: "'vagrant' not in installed_packages.stdout_lines"

- name: Install chef-dk
  command: yaourt --noconfirm -S chef-dk
  sudo: yes
  sudo_user: makepkg
  when: "'chef-dk' not in installed_packages.stdout_lines"

- name: Install Vagrant plugins
  command: 'vagrant plugin install {{ item }}'
  with_items:
    - vagrant-berkshelf
    - vagrant-omnibus
  sudo: yes
  sudo_user: '{{ user }}'
  when: "'{{ item }}' not in installed_vagrant_plugins.stdout"

- name: Install VirtualBox (for Vagrant)
  pacman: name=virtualbox state=present

- name: Set up autoloading of VirtualBox host modules
  copy: src=files/virtualbox/host-modules dest=/etc/modules-load.d/virtualbox-host.conf
