---
- name: Install cronie
  pacman: name=cronie state=present

- name: Enable cronie
  service: name=cronie state=started enabled=yes

- name: Cron to download updates
  copy: src=files/cron/download-updates dest=/etc/cron.d/download-updates

- name: Install reflector for mirror list autoupdate
  pacman: name=reflector state=present

- name: Cron to update mirror list
  copy: src=files/cron/reflector dest=/etc/cron.d/reflector
