# Missing:
# exuberant-ctags
# fasd
# fortune
# gcalcli
# kpcli
# lm-sensors
# spell-pt
# alsamixer

- name: install utilities
  pacman: name={{ item }} state=present
  with_items:
    - atop
    - abook
    - ack
    - alsa-utils
    - aria2
    - aspell
    - aspell-en
    - aspell-es
    - aspell-fr
    - aspell-it
    - autoconf
    - autofs
    - bc
    - bitlbee
    - cmake
    - colordiff
    - curl
    - dosfstools
    - elinks
    - git
    - lsof
    - gnupg
    - gparted
    - htop
    - dnsutils
    - iftop
    - imagemagick
    - iptraf-ng
    - irssi
    - ispell
    - isync
    - lftp
    - mc
    - mpd
    - mutt
    - ncmpcpp
    - newsbeuter
    - nfs-utils
    - nmap
    - nodejs
    - notmuch
    - ntfsprogs
    - ntp
    - p7zip
    - parted
    - perl-datetime
    - perl-image-exiftool
    - pinentry
    - polipo
    - pulseaudio
    - pydf
    - python2
    - python2-pip
    - ranger
    - rsync
    - rtorrent
    - screen
    - scrot
    - sudo
    - task
    - tmux
    - tree
    - unrar
    - unzip
    - vim
    - wicd
    - zsh
    - zsh-syntax-highlighting
  sudo: true
  sudo_user: "{{ ansible_user_id }}"
