---
- name: Install media applications
  apt: name={{ item }} state=present
  with_items:
    - mplayer2
    - mpd
    - mpc
  when: user == "chris"

- name: Install zathura
  apt: name=zathura state=present
