---
- name: Install media applications
  pacman: name={{ item }} state=present
  with_items:
    - mpv
    - mpd
    - mpc

- name: Install zathura
  pacman: name={{ item }} state=present
  with_items:
    - zathura
    - zathura-pdf-mupdf
