---
- name: Automatically get DHCP lease
  service: name=dhcpcd state=started enabled=yes
  when: not wifi

- name: Install wireless tools
  apt: name={{ item }} state=present
  with_items:
    - wicd-curses
    - wicd-daemon
  when: wifi

- name: Enable wicd
  service: name=wicd state=started enabled=yes
  when: wifi

- name: Add local user to netdev
  user: name={{ user }} groups=netdev append=yes
  when: wifi

- name: Install dnsmasq for DNS caching
  apt: name=dnsmasq state=present

- name: Set up DNS caching
  copy: src=files/network/dnsmasq.conf dest=/etc/dnsmasq.conf

- name: Start and enable dnsmasq
  service: name=dnsmasq state=started enabled=yes

- name: Set up DNS resolvers
  copy: src=files/network/resolv.conf.head dest=/etc/resolv.conf.head
