---
- name: Copy pacman configuration
  template: src=files/pacman.conf dest=/etc/pacman.conf
  sudo: yes
  sudo_user: "{{ ansible_user_id }}"

#- name: Update package lists
  #pacman: update_cache=yes
  #sudo: yes
  #sudo_user: root
  #sudo_user: "{{ ansible_user_id }}"
  #changed_when: false

# https://stackoverflow.com/questions/18839509/where-can-i-get-a-list-of-ansible-pre-defined-variables
# https://gist.github.com/nanobeep/3b3d614a709086ff832a
- shell: sh -c "sudo pacman -Syy"
  become: yes
  become_user: "{{ ansible_user_id }}"
  become_method: sudo
