---
- name: Install rbenv
  command: aur {{ item }}
  with_items:
    - rbenv
    - ruby-build
  when: user == "chris"

- name: Install ruby 2.1.2 using rbenv
  command: {{ item }}
  with_items:
    - rbenv install 2.1.2
    - rbenv rehash
    - rbenv global 2.1.2
  sudo: yes
  sudo_user: "{{ user }}"
  when: user == "chris"

- name: Install bundler
  shell: eval "$(rbenv init -)" && gem install bundler && rbenv rehash
  sudo: yes
  sudo_user: "{{ user }}"
  when: user == "chris"
