---
- name: Install Xorg base
  apt: name={{ item }} state=present
  with_items:
    - xserver-xorg
    - x11-xserver-utils
    - xinit
    - dbus-x11

- name: Blacklist nouveau Xorg driver
  kernel_blacklist: name=nouveau state=present
  when: model == "Vostro 3700"

- name: Set up Xorg for Vostro 3700
  apt: name={{ item }} state=present
  with_items:
    - xserver-xorg-video-intel
    - xserver-xorg-input-synaptics
  when: model == "Vostro 3700"

- name: Set up Xorg for XPS 8500
  apt: name=xserver-xorg-video-nouveau state=present
  when: model == "XPS 8500"

- name: Install VirtualBox guest utilities
  apt: name={{ item }} state=present
  with_items:
    - virtualbox-guest-utils
    - virtualbox-guest-x11
    - virtualbox-guest-dkms
  when: model == "VirtualBox"

- name: Set up autoloading of VirtualBox modules
  lineinfile: dest=/etc/modules line={{ item }}
  with_items:
    - vboxguest
    - vboxsf
    - vboxvideo
  when: model == "VirtualBox"
