---
- name: Install Xorg base
  apt: name={{ item }} state=present
  with_items:
    - xserver-xorg
    - x11-xserver-utils
    - xinit

- name: Blacklist nouveau Xorg driver
  kernel_blacklist: name=nouveau state=present
  when: model == "Vostro 3700"

- name: Set up Xorg for Vostro 3700
  apt: name={{ item }} state=present
  with_items:
    - xserver-xorg-video-intel
    - xserver-xorg-input-synaptics
  when: model == "Vostro 3700"

- name: Set up Xorg for XPS 8500
  apt: name={{ item }} state=present
  with_items:
    - xserver-xorg-video-nouveau
  when: model == "XPS 8500"

- name: Install VirtualBox guest utilities
  apt: name=virtualbox-guest-utils state=present
  when: model == "VirtualBox"

- name: Set up autoloading of VirtualBox modules
  copy: src=files/virtualbox/modules dest=/etc/modules-load.d/virtualbox-guest.conf
  when: model == "VirtualBox"
