---
- name: Install Xorg base
  pacman: name={{ item }} state=present
  with_items:
    - xorg-server
    - xorg-xprop
    - xorg-xmodmap
    - xorg-xrandr
    - xorg-xinit
    - xorg-xev
    - xorg-xset
    - xorg-xrdb

- name: Blacklist nouveau Xorg driver
  kernel_blacklist: name=nouveau state=present
  when: model == "Vostro 3700"

- name: Set up Xorg for Vostro 3700
  pacman: name={{ item }} state=present
  with_items:
    - xf86-video-intel
    - xf86-input-synaptics
  when: model == "Vostro 3700"

- name: Set up Xorg for XPS 8500
  pacman: name={{ item }} state=present
  with_items:
    - xf86-video-nouveau
  when: model == "XPS 8500"

- name: Set up Xorg for Parallels
  pacman: name=xf86-video-vesa state=present
  when: model == "Parallels"

- name: Install VirtualBox guest utilities
  pacman: name=virtualbox-guest-utils state=present
  when: model == "VirtualBox"

- name: Set up autoloading of VirtualBox modules
  copy: src=files/virtualbox/guest-modules dest=/etc/modules-load.d/virtualbox-guest.conf
  when: model == "VirtualBox"

- name: Configure vboxservice
  service: name=vboxservice state=started enabled=yes
  when: model == "VirtualBox"

- name: Depmod
  command: depmod
  changed_when: false
